services:
  web:
    image: $DOCKER_IMAGE_BACKEND
    environment:
      CI: "true"
    volumes:
      - ./:/code
      - ./ci-share/:/ci-share/
      # - ./coverage/:/code/coverage/

  worker: !reset null
  worker-beat: !reset null
