[project]
name = "alert-hub-backend"
version = "0.1.0"
description = ""
authors = [{ name = "IFRC" }]
requires-python = "~=3.11"
readme = "README.md"
dependencies = [
    "Django>=4.2,<4.3",
    "celery~=5.3",
    "flower",
    "django-celery-beat",
    "django-cors-headers",
    "django-environ",
    "django-redis>=5.3.0,<6",
    "django-storages[s3, azure]",
    "django-admin-autocomplete-filter",
    "django-modeltranslation==0.19.14",
    "iso639-lang>=2.1.0,<2.2.0",
    "psycopg2-binary>=2.9.9,<3",
    "pytz",
    "colorlog",
    "requests",
    "strawberry-graphql-django==0.49.1",
    "strawberry-graphql==0.257.0",
    "sentry-sdk",
    "djangorestframework",
    "validators",
    "django-health-check",
    "psutil",
    "uwsgi",
    "django-premailer",
    "user-agents",
    "factory-boy",
    "azure-identity",
]

[dependency-groups]
dev = [
    "pytest",
    "ipython",
    "pytest-profiling",
    "pytest-ordering",
    "pytest-django",
    "django-stubs==4.2.6",
    "celery-types",
]

[tool.uv]
package = false

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
exclude = [
    "**/__pycache__",
    "**/snap_test_*.py",
    ".venv/",
    "legacy/",
    "**/migrations/*.py",
]

[tool.black]
line-length = 125
skip-string-normalization = true
# NOTE: Update in .pre-commit-config.yaml as well
extend-exclude = "(__pycache__|.*snap_test_.*\\.py|.+\\/.+\\/migrations\\/.*)"

[tool.isort]
profile = "black"
multi_line_output = 3
skip = [
    "**/__pycache__",
    "**/snap_test_*.py",
    ".venv/",
    "legacy/",
    "**/migrations/*.py",
]

[tool.pyright]
exclude = [
    "**/__pycache__",
    "**/snap_test_*.py",
    ".venv/",
    "legacy/",
    "**/migrations/*.py",
]
reportMissingImports = true
reportMissingTypeStubs = false
venvPath = "."
venv = ".venv"
reportPrivateImportUsage = "warning"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "main.settings"
log_cli = true
