# Generated by Django 4.2.3 on 2023-08-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_cache', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapFeedAlertDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cap_feed_alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CapFeedDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.TextField()),
                ('multipolygon', models.TextField()),
                ('max_latitude', models.FloatField(blank=True, null=True)),
                ('max_longitude', models.FloatField(blank=True, null=True)),
                ('min_latitude', models.FloatField(blank=True, null=True)),
                ('min_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cap_feed_district',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='capfeedalert',
            options={},
        ),
    ]
