# Generated by Django 4.2.11 on 2024-03-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CapFeedAdmin1',
        ),
        migrations.DeleteModel(
            name='CapFeedAlert',
        ),
        migrations.DeleteModel(
            name='CapFeedAlertadmin1',
        ),
        migrations.DeleteModel(
            name='CapFeedAlertinfo',
        ),
        migrations.DeleteModel(
            name='CapFeedCountry',
        ),
    ]
