kind: Secret
apiVersion: v1
metadata:
  name: {{ template "ifrcgo-alert-hub.fullname" . }}-api-secret
  labels:
    component: api-deployment
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ required "secrets.DJANGO_SECRET_KEY" .Values.secrets.DJANGO_SECRET_KEY | quote }}
  # Database
  DB_NAME: {{ required "secrets.DB_NAME" .Values.secrets.DB_NAME | quote }}
  DB_USER: {{ required "secrets.DB_USER" .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ required "secrets.DB_PASSWORD" .Values.secrets.DB_PASSWORD | quote }}
  DB_HOST: {{ required "secrets.DB_HOST" .Values.secrets.DB_HOST | quote }}
  DB_PORT: {{ required "secrets.DB_PORT" .Values.secrets.DB_PORT | quote }}
  # Sentry
  SENTRY_DSN: {{ required "secrets.SENTRY_DSN" .Values.secrets.SENTRY_DSN | quote }}
  # Email
  EMAIL_HOST: {{ required "secrets.EMAIL_HOST" .Values.secrets.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ required "secrets.EMAIL_PORT" .Values.secrets.EMAIL_PORT | quote }}
  EMAIL_HOST_USER: {{ required "secrets.EMAIL_HOST_USER" .Values.secrets.EMAIL_HOST_USER | quote }}
  EMAIL_HOST_PASSWORD: {{ required "secrets.EMAIL_HOST_PASSWORD" .Values.secrets.EMAIL_HOST_PASSWORD | quote }}
  # Redis
  {{- if .Values.redis.enabled }}
  CELERY_BROKER_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}/6379/0"
  CACHE_REDIS_URL: "redis://{{ printf "%s-master" (include "common.names.fullname" .Subcharts.redis) }}/6379/1"
  {{- else }}
  CELERY_BROKER_URL: {{ required "env.CELERY_BROKER_URL" .Values.env.CELERY_BROKER_URL | quote }}
  CACHE_REDIS_URL: {{ required "env.CACHE_REDIS_URL" .Values.env.CACHE_REDIS_URL | quote }}
  {{- end }}
