# This extends ./go-deploy.yaml

app:
  environment: staging

  worker:
    queueDefaults:
      resources:
        requests:
          memory: 512Mi
    queues:
      feeds:
        replicaCount: 2

  env:
    UPTIME_WORKER_HEARTBEAT: ""  # Not tracking staging for now
    DEFAULT_FROM_EMAIL: Alerthub Staging <hazard.alerts@ifrc.org>
    # Sentry
    SENTRY_TRACES_SAMPLE_RATE: "0.5"
    SENTRY_PROFILE_SAMPLE_RATE: "0.5"
