{{- if .Values.worker.enabled }}

{{- range $queue_name, $config := .Values.worker.queues }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-alert-hub.fullname" $ }}-worker-{{ $queue_name }}
  labels:
    app: {{ include "ifrcgo-alert-hub.fullname" $ }}
    component: worker
    queue: {{ $queue_name }}
    environment: {{ $.Values.environment }}
    release: {{ $.Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ifrcgo-alert-hub.fullname" $ }}
      component: worker
      queue: {{ $queue_name }}
  template:
    metadata:
      labels:
        app: {{ include "ifrcgo-alert-hub.fullname" $ }}
        component: worker
        queue: {{ $queue_name }}
        {{- if $.Values.serviceAccount.create }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      containers:
        - name: worker
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          command: ["/code/deploy/run_worker.sh"]
          # TODO: livenessProbe
          resources:
            {{- toYaml $config.resources | nindent 12 }}
          env:
            - name: DJANGO_APP_TYPE
              value: worker
            - name: CELERY_ARGS
              value: {{ required "worker.queues.*.celeryArgs" $config.celeryArgs | quote }}
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-alert-hub.secretname" $ }}
            - configMapRef:
                name: {{ template "ifrcgo-alert-hub.fullname" $ }}-api-configmap

      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "ifrcgo-alert-hub.serviceAccountName" $ }}
      {{- end }}

      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}

{{- end }}
