{{- if .Values.worker.enabled }}
{{- if .Values.worker.flower.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ifrcgo-alert-hub.fullname" . }}-celery-flower
  labels:
    app: {{ include "ifrcgo-alert-hub.fullname" . }}
    component: worker-flower
    environment: {{ .Values.environment }}
    release: {{ .Release.Name }}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "ifrcgo-alert-hub.fullname" . }}
      component: worker-flower
  template:
    metadata:
      labels:
        app: {{ include "ifrcgo-alert-hub.fullname" . }}
        component: worker-flower
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          command: ["celery", "-A", "main", "flower", "--port=8000"]
          # TODO: livenessProbe
          resources:
            {{- toYaml .Values.worker.flower.resources | nindent 12 }}
          env:
            - name: DJANGO_APP_TYPE
              value: worker
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-alert-hub.secretname" . }}
            - configMapRef:
                name: {{ template "ifrcgo-alert-hub.fullname" . }}-api-configmap

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
{{- end }}
