{{- range $hookName, $hook := .Values.argoHooks }}

{{- if $hook.enabled }}

---
apiVersion: batch/v1
kind: Job
metadata:
  {{- if $hook.preserveHistory }}
  generateName: {{ template "ifrcgo-alert-hub.fullname" $ }}-{{ $hookName }}-
  {{- else }}
  name: {{ template "ifrcgo-alert-hub.fullname" $ }}-{{ $hookName }}
  {{- end }}
  annotations:
    argocd.argoproj.io/hook: {{ $hook.hook }}
spec:
  template:
    metadata:
      labels:
        {{- if $.Values.serviceAccount.create }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      restartPolicy: "Never"
      containers:
        - name: {{ $hookName }}
          image: "{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
          command: {{ toYaml $hook.command | trim | nindent 12 }}
          resources:
            requests:
              cpu: {{ default $.Values.api.resources.requests.cpu $hook.requestsCpu }}
              memory: {{ default $.Values.api.resources.requests.memory $hook.requestsMemory }}
            limits:
              cpu: {{ default $.Values.api.resources.limits.cpu $hook.limitsCpu }}
              memory: {{ default $.Values.api.resources.limits.memory $hook.limitsMemory }}
          env:
            - name: DJANGO_APP_TYPE
              value: hook
          envFrom:
            - secretRef:
                name: {{ template "ifrcgo-alert-hub.secretname" $ }}
            - configMapRef:
                name: {{ template "ifrcgo-alert-hub.fullname" $ }}-api-configmap

      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: {{ include "ifrcgo-alert-hub.serviceAccountName" $ }}
      {{- end }}

      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}

{{- end }}
