# Generated by Django 4.2.11 on 2024-04-16 07:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='admin1',
            name='ifrc_go_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='ifrc_go_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='region',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='region',
            name='ifrc_go_id',
            field=models.IntegerField(editable=False, null=True, unique=True),
        ),
    ]
