# Generated by Django 4.2.11 on 2024-04-21 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0002_admin1_bbox_admin1_ifrc_go_id_country_bbox_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cap_feed.continent'),
        ),
    ]
