# Generated by Django 4.2.11 on 2024-04-21 11:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0003_alter_country_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin1',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
