# Generated by Django 4.2.11 on 2024-04-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0004_admin1_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin1',
            name='max_latitude',
        ),
        migrations.RemoveField(
            model_name='admin1',
            name='max_longitude',
        ),
        migrations.RemoveField(
            model_name='admin1',
            name='min_latitude',
        ),
        migrations.RemoveField(
            model_name='admin1',
            name='min_longitude',
        ),
        migrations.RemoveField(
            model_name='admin1',
            name='multipolygon',
        ),
        migrations.RemoveField(
            model_name='admin1',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='country',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='multipolygon',
        ),
        migrations.RemoveField(
            model_name='country',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='region',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='region',
            name='polygon',
        ),
    ]
