# Generated by Django 4.2.11 on 2024-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0005_remove_admin1_max_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
