# Generated by Django 4.2.13 on 2024-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0006_alert_is_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='name_ar',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_es',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_fr',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ar',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_es',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fr',
            field=models.CharField(null=True),
        ),
    ]
