# Generated by Django 4.2.13 on 2024-08-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0007_country_name_ar_country_name_en_country_name_es_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(condition=models.Q(('is_expired', False)), fields=['is_expired'], name='cap_feed_alert_not_expired_idx'),
        ),
    ]
