# Generated by Django 4.2.13 on 2024-11-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0008_alert_cap_feed_alert_not_expired_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_processed_by_subscription',
            field=models.BooleanField(null=True),
        ),
    ]
