# Generated by Django 4.2.13 on 2024-11-22 05:05

from django.db import migrations, models


def set_default_for_existing_alerts(apps, _):
    Alert = apps.get_model('cap_feed', 'Alert')
    Alert.objects.update(is_processed_by_subscription=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0008_alert_cap_feed_alert_not_expired_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_processed_by_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_default_for_existing_alerts),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(condition=models.Q(('is_processed_by_subscription', False)), fields=['is_processed_by_subscription'], name='cap_feed_alert_subscription_ix'),
        ),
    ]
