# Generated by Django 4.2.13 on 2024-11-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0009_alert_is_processed_by_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='is_processed_by_subscription',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(condition=models.Q(('is_processed_by_subscription', False)), fields=['is_processed_by_subscription'], name='cap_feed_alert_subscription_ix'),
        ),
    ]
