# Generated by Django 4.2.13 on 2024-11-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0010_alter_alert_is_processed_by_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='category',
            field=models.CharField(choices=[('Geo', 'Geo'), ('Met', 'Met'), ('Safety', 'Safety'), ('Security', 'Security'), ('Rescue', 'Rescue'), ('Fire', 'Fire'), ('Health', 'Health'), ('Env', 'Env'), ('Transport', 'Transport'), ('Infra', 'Infra'), ('CBRNE', 'CBRNE'), ('Other', 'Other')], db_index=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='certainty',
            field=models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')], db_index=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='severity',
            field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')], db_index=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='urgency',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')], db_index=True),
        ),
    ]
