# Generated by Django 4.2.21 on 2025-10-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0012_admin1_emma_id_admin1_fips_code_admin1_nuts1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='author_email',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feed',
            name='author_name',
            field=models.CharField(blank=True, default=''),
        ),
    ]
