# Generated by Django 4.2.21 on 2026-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0013_feed_archived_at_feed_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='has_preparedness_messages',
            field=models.BooleanField(default=False, help_text='Flags whether https://preparemessages.ifrc.org includes data for this country. Updated automatically by the system.'),
        ),
    ]
