# Generated by Django 4.2.21 on 2026-02-03 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0014_country_has_preparedness_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
