apiVersion: v2
name: ifrcgo-alert-hub-helm
description: "Helm Chart to deploy the IFRC GO Risk Module Infrastructure"
type: application
version: 0.1.1-SET-BY-CICD  # managed by release.sh
sources:
  - https://github.com/IFRCGo/alert-hub-backend

dependencies:
  - name: banjo-helm
    alias: app
    version: 0.3.0
    repository: oci://ghcr.io/toggle-corp
