# This extends ./values-go-deploy.yaml

app:
  environment: production

  api:
    replicaCount: 2
    resources:
      requests:
        memory: 2Gi  # XXX: Large payload from PowerBI
      limits:
        memory: 2Gi

  worker:
    queueDefaultResources:
      requests:
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 1Gi

  env:
    UPTIME_WORKER_HEARTBEAT: "https://heartbeat.uptimerobot.com/m798706781-9c8ce80c58dd15e073bcd9f9adae1b0dd78dba47"
    DEFAULT_FROM_EMAIL: Alerthub <hazard.alerts@ifrc.org>
    # Sentry
    SENTRY_TRACES_SAMPLE_RATE: "0.2"
    SENTRY_PROFILE_SAMPLE_RATE: "0.2"
