environment: prod

image:
  name: SET-BY-CICD-IMAGE
  tag: SET-BY-CICD-TAG

ingress:
  enabled: false
  host:
  className:
  tls:
    enabled: false
    secretName:

redis:
  enabled: true
  architecture: standalone
  fullnameOverride: alert-hub-redis
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: .5Gi
      storageClass:

postgresql:
  enabled: false
  fullnameOverride: ""
  architecture: standalone
  auth:
    postgresPassword: ""
    username: ""
    password: ""
    database: ""
  primary:
    persistence:
      enabled: true
      storageClass: ""
      size: 8Gi

api:
  enabled: true
  replicaCount: 1
  containerPort: 80
  resources:
    requests:
      cpu: "2"
      memory: 0.5Gi
    limits:
      cpu: "2"
      memory: 1Gi

worker:
  enabled: true
  beat:
    resources:
      requests:
        cpu: "1"
        memory: 0.5Gi
      limits:
        cpu: "1"
        memory: 1Gi
  flower:
    enabled: true
    resources:
      requests:
        cpu: "0.1"
        memory: 0.5Gi
      limits:
        cpu: "1"
        memory: 1Gi
  queues:
    # NOTE: Make sure keys are lowercase
    default:
      enabled: true
      replicaCount: 1
      celeryArgs: "-Q default --concurrency 4 --max-tasks-per-child 10"
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi
    feeds:
      enabled: true
      replicaCount: 2
      celeryArgs: "-Q feeds --concurrency 4 --max-tasks-per-child 10 --soft-time-limit 300 --time-limit 500"
      resources:
        requests:
          cpu: "2"
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi

argoHooks:
  # NOTE: Make sure keys are lowercase
  db-migrate:
    enabled: true
    hook: PostSync
    preserveHistory: true
    command: ["./manage.py", "migrate"]
  collect-static:
    enabled: true
    hook: PostSync
    command: ["./manage.py", "collectstatic", "--noinput"]

env:
  # DJANGO_APP_ENVIRONMENT: using .environment
  # APP_RELEASE: using .image.tag
  DJANGO_DEBUG: false
  DJANGO_TIME_ZONE: UTC
  # App Domain
  APP_DOMAIN:
  APP_HTTP_PROTOCOL: https
  APP_FRONTEND_HOST:
  DJANGO_ALLOWED_HOSTS: "*"
  SESSION_COOKIE_DOMAIN:
  CSRF_COOKIE_DOMAIN:
  # CORS
  CORS_ALLOWED_ORIGINS:
  CORS_ALLOWED_ORIGIN_REGEXES:
  # Misc
  UPTIME_WORKER_HEARTBEAT:
  EMAIL_USE_TLS: true
  DEFAULT_FROM_EMAIL:
  # Sentry
  SENTRY_TRACES_SAMPLE_RATE: 0.2
  SENTRY_PROFILE_SAMPLE_RATE: 0.2
# NOTE: Used to pass additional configs to api/worker containers
# NOTE: Not used by azure vault
envAdditional:
  # USE_S3_BUCKET: "true"

secretsName: ""
secrets:
  DJANGO_SECRET_KEY:
  # Database
  DB_NAME:
  DB_USER:
  DB_PASSWORD:
  DB_HOST:
  DB_PORT:
  # Email
  EMAIL_HOST:
  EMAIL_PORT:
  EMAIL_HOST_USER:
  EMAIL_HOST_PASSWORD:
  # Sentry
  SENTRY_DSN:
  # Redis (Provide: if not redis.enabled)
  # - Celery
  CELERY_BROKER_URL:
  # - Cache
  CACHE_REDIS_URL:
  # Hcaptcha
  HCAPTCHA_SITEKEY:
  HCAPTCHA_SECRET:
# NOTE: Used to pass additional secrets to api/worker containers
# NOTE: Not used by azure vault
secretsAdditional:
  # AWS_S3_ACCESS_KEY_ID: "VERY-SENSITIVE-KEY-ID"

# Azure configurations
azure:
  aksSecretsProviderAvailable: false
  keyvault:
    name: ""
    clientId: ""
    tenantId: ""

serviceAccount:
  # Specifies whether a service account should be created
  # Required when using workload identity to access Azure Key Vault Secrets
  create: false
  automount: true
  annotations:
    azure.workload.identity/client-id : "<workload_identity_client_id>"
  labels:
    azure.workload.identity/use: "true"
  name: ""
