environment: sandbox

image:
  name: ghcr.io/ifrcgo/alert-hub-backend
  tag: develop.448e946

ingress:
  enabled: true
  host: alert-hub-sandbox.ifrc.org
  ingressClassName: webapprouting.kubernetes.azure.com

env:
  # DJANGO_APP_ENVIRONMENT: using .environment
  # APP_RELEASE: using .image.tag
  DJANGO_DEBUG: false
  DJANGO_TIME_ZONE: UTC
  # App Domain
  APP_DOMAIN: alert-hub-sandbox.ifrc.org
  APP_HTTP_PROTOCOL: https
  APP_FRONTEND_HOST: dummy.com
  DJANGO_ALLOWED_HOSTS: "*"
  SESSION_COOKIE_DOMAIN: .dummy.com
  CSRF_COOKIE_DOMAIN: .dummy.com
  # CORS
  CORS_ALLOWED_ORIGINS: dummy.com
  # Misc
  DEFAULT_FROM_EMAIL: dummy@dummy.com

secretsName: ""
secrets:
  DJANGO_SECRET_KEY: dummy-secret-key
  # Database
  DB_NAME: dummy
  DB_USER: dummy
  DB_PASSWORD: dummy
  DB_HOST: dummy
  DB_PORT: 5432
  # Email
  EMAIL_HOST: dummy.com
  EMAIL_PORT: 443
  EMAIL_HOST_USER: dummy
  EMAIL_HOST_PASSWORD: dummy
  # Sentry
  SENTRY_DSN: dummy.com/dummy-id

# Azure configurations
azure:
  aksSecretsProviderAvailable: true
  keyvault:
    name: "alert-hub-playground-key"
    clientId: "f1b1a632-68d6-4e5d-8a1e-d416e98b41a4"
    tenantId: "a2b53be5-734e-4e6c-ab0d-d184f60fd917"

serviceAccount:
  # Specifies whether a service account should be created
  # Required when using workload identity to access Azure Key Vault Secrets
  create: true
  automount: true
  annotations:
    azure.workload.identity/client-id : "f1b1a632-68d6-4e5d-8a1e-d416e98b41a4"
  labels:
    azure.workload.identity/use: "true"
  name: ""
