environment: production
fullnameOverride: ifrcgo-alert-hub

ingress:
  enabled: true
  className: nginx
  tls:
    enabled: true
    secretName:
  # Needs to be defined at go-deploy
  # host: alerthub-stage-api.ifrc.org

redis:
  master:
    resourcesPreset: micro  # https://github.com/bitnami/charts/blob/main/bitnami/common/templates/_resources.tpl#L16

# FIXME: Use proper requests.cpu
worker:
  beat:
    resources:
      requests:
        cpu: "0.1"
        memory: 0.5Gi
      limits:
        cpu: "1"
        memory: 1Gi
  flower:
    resources:
      requests:
        cpu: "0.1"
        memory: 0.5Gi
      limits:
        cpu: "1"
        memory: 1Gi
  queues:
    # NOTE: Make sure keys are lowercase
    default:
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
    feeds:
      replicaCount: 2
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "4"
          memory: 2Gi

api:
  resources:
    requests:
      cpu: "2"
      memory: 1Gi
    limits:
      cpu: "4"
      memory: 2Gi

env:
  DJANGO_DEBUG: false
  # Misc
  UPTIME_WORKER_HEARTBEAT: https://heartbeat.uptimerobot.com/m798706781-9c8ce80c58dd15e073bcd9f9adae1b0dd78dba47
  DEFAULT_FROM_EMAIL: Alerthub <hazard.alerts@ifrc.org>
  # Sentry
  SENTRY_TRACES_SAMPLE_RATE: 0.2
  SENTRY_PROFILE_SAMPLE_RATE: 0.2
  # Needs to be defined at go-deploy
  # # App Domain
  # APP_FRONTEND_HOST: https://alerthub.ifrc.org
  # APP_DOMAIN: alerthub-api.ifrc.org
  # DJANGO_ALLOWED_HOSTS: alerthub-api.ifrc.org
  # SESSION_COOKIE_DOMAIN: .ifrc.org
  # CSRF_COOKIE_DOMAIN: .ifrc.org
  # # CORS
  # CORS_ALLOWED_ORIGINS: https://alerthub.ifrc.org
