# Generated by Django 4.2.13 on 2024-11-24 09:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0009_alert_is_processed_by_subscription'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useralertsubscription',
            name='alert_filters',
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_admin1s',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Geo', 'Geo'), ('Met', 'Met'), ('Safety', 'Safety'), ('Security', 'Security'), ('Rescue', 'Rescue'), ('Fire', 'Fire'), ('Health', 'Health'), ('Env', 'Env'), ('Transport', 'Transport'), ('Infra', 'Infra'), ('CBRNE', 'CBRNE'), ('Other', 'Other')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_certainties',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cap_feed.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_severities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')]), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='useralertsubscription',
            name='filter_alert_urgencies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')]), blank=True, default=list, size=None),
        ),
    ]
