# Generated by Django 4.2.13 on 2024-11-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_useralertsubscription_alert_filters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralertsubscription',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
