name: CI

on:
  pull_request:
  # NOTE: For push/publish, see ./helm-publish.yml

jobs:
  _:
    uses: toggle-corp/banjo-action/.github/workflows/pipeline.yml@v0.1.1
    with:
      # Job: Pre-commit
      pre_commit__apt_packages: "gdal-bin libgdal-dev"
      # Job: Docker
      docker__wait_cmd: "./manage.py wait_for_resources --db --cache --celery-broker"
      docker__migration_dummy_test: "main.tests.test_fake"
      docker__run_graphql_check: true
      docker__run_openapi_check: false
      docker__compose_file: "docker-compose.yml:./.github/docker-compose.yml"
      docker__compose_service_name: "web"
      docker__compose_test_cmd: "/code/scripts/run_tests.sh"
      # Job: Helm
      helm__chart_directory: "./helm"
