name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - project/*

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  _:
    uses: toggle-corp/banjo-action/.github/workflows/pipeline.yml@v0.4.0
    with:
      # -- Same as CI (./ci.yml)
      # Job: Pre-commit
      pre_commit__apt_packages: "gdal-bin libgdal-dev"
      # Job: Docker
      docker__wait_cmd: "./manage.py wait_for_resources --db --cache --celery-broker"
      docker__migration_dummy_test: "main.tests.test_fake"
      docker__run_graphql_check: true
      docker__run_openapi_check: false
      docker__compose_file: "docker-compose.yml:./.github/docker-compose.yml"
      docker__compose_service_name: "web"
      docker__compose_test_cmd: "/code/scripts/run_tests.sh"
      # Job: Helm
      helm__chart_directory: "./helm"
      # -- Publish
      docker__push: true
      helm__push: true
